ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'AWS_US';
ALTER ACCOUNT SET ALLOW_CLIENT_MFA_CACHING = TRUE;
SHOW MFA METHODS FOR USER SMNADUKUDY;

CREATE USER MACHINEUSER 
TYPE = SERVICE
COMMENT = 'Machine user for CLI automation';

ALTER USER MACHINEUSER SET RSA_PUBLIC_KEY='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwY9nOGlUc4C1X/W7a1PH
Pm7oxn1aAOBT6Dlh0FU3p6JPhcw/Jnf/+TV5DHsAZP7jAS920TQDKG0i0WEs9NfK
W9GNrcrk7karzGPtUh87gH4k3kCZeQdBzE6VhG+ap5rxEMiFa0MRinpldBi52ECz
qONDV/bl5OOlGlEgLzII8Iwo01GddEvIAKRV3bRCslN2JhjdTQw8RrSAs0g0+bel
PAH9R5cIli3hZsvcGevPGWiLzFSB8JSWNTWIZgr2AMzMU/Bh4XJLwEU36IJ0DuaY
fKgG/9v54YMrVe+veUsUfG3//GvUMGYZXyLuTsf80QpHmSRu50C2kOtGb1Xa77zr
RwIDAQAB';

desc user MACHINEUSER;

CREATE ROLE IF NOT EXISTS SERVICE_ROLE;

  ALTER USER MACHINEUSER
  SET DEFAULT_ROLE = SERVICE_ROLE;

  GRANT ROLE SERVICE_ROLE TO USER MACHINEUSER;

  GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SERVICE_ROLE;

  GRANT USAGE ON DATABASE ANOMALIES TO ROLE SERVICE_ROLE;
  GRANT USAGE ON SCHEMA ANOMALIES.PUBLIC TO ROLE SERVICE_ROLE;

  GRANT SELECT ON ALL TABLES IN SCHEMA ANOMALIES.PUBLIC TO ROLE SERVICE_ROLE;
  GRANT SELECT ON FUTURE TABLES IN SCHEMA ANOMALIES.PUBLIC TO ROLE SERVICE_ROLE;

 GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE SERVICE_ROLE;
